"""Cognitive annotation ingestion pipeline.

Contract: the annotation JSON is generated by a specialized upstream AI and is
treated as source-of-truth metadata. This module MUST NOT recompute, alter or
infer any of its fields — it only validates the minimum shape, stores the
payload verbatim, and exposes it read-only to the rest of the platform.

Extra fields are preserved (extra="allow") so the schema can evolve without
platform changes. Every stored record carries `schema_version` for
version-aware consumers.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class ItemAlternative(BaseModel):
    model_config = ConfigDict(extra="allow")
    id: str
    texto: str | None = None


class ItemFonte(BaseModel):
    model_config = ConfigDict(extra="allow")
    banca: str
    ano: int
    caderno: str | None = None
    numero: int | None = None


class Item(BaseModel):
    model_config = ConfigDict(extra="allow")
    id: str
    fonte: ItemFonte | None = None
    disciplina: str | None = None
    tema_objetivo: str | None = None
    conteudo_curricular: list[str] = Field(default_factory=list)
    enunciado: str | None = None
    alternativas: list[ItemAlternative] = Field(default_factory=list)
    gabarito: str | None = None


class EstruturaCognitiva(BaseModel):
    model_config = ConfigDict(extra="allow")
    nivel_abstracao: str | None = None
    carga_cognitiva: str | None = None
    dificuldade_global: float | None = None
    tipo_raciocinio_predominante: list[str] = Field(default_factory=list)
    operacoes_cognitivas: list[str] = Field(default_factory=list)


class ProcessoAtivado(BaseModel):
    model_config = ConfigDict(extra="allow")
    cognitive_process_id: str
    papel: str | None = None
    prioridade: int | None = None
    peso_ativacao: float | None = None
    confianca: float | None = None
    dificuldade_local: float | None = None
    evidencias: list[str] = Field(default_factory=list)


class DistratorAnalise(BaseModel):
    model_config = ConfigDict(extra="allow")
    alternativa: str
    error_type_id: int | None = None
    cognitive_process_falhou: list[str] = Field(default_factory=list)
    explicacao: str | None = None


class CaracteristicasItem(BaseModel):
    model_config = ConfigDict(extra="allow")
    possui_texto: bool | None = None
    possui_tabela: bool | None = None
    possui_grafico: bool | None = None
    possui_imagem: bool | None = None
    possui_formula: bool | None = None
    contexto_cotidiano: bool | None = None
    necessita_calculo: bool | None = None
    necessita_estimativa: bool | None = None


class Intervencao(BaseModel):
    model_config = ConfigDict(extra="allow")
    cognitive_process_id: str
    tipo: str | None = None


class Pedagogia(BaseModel):
    model_config = ConfigDict(extra="allow")
    principal_intervencao: Intervencao | None = None
    explicacao_resolucao: str | None = None
    misconceptions: list[str] = Field(default_factory=list)


class QualidadeAnotacao(BaseModel):
    model_config = ConfigDict(extra="allow")
    confianca_global: float | None = None
    revisado_humano: bool | None = None
    revisor: str | None = None
    data: str | None = None


class AnnotationPayload(BaseModel):
    """Full annotation contract. `extra='allow'` at every level so upstream
    additions never break ingestion."""
    model_config = ConfigDict(extra="allow")
    schema_version: str
    item: Item
    estrutura_cognitiva: EstruturaCognitiva | None = None
    processos_ativados: list[ProcessoAtivado] = Field(default_factory=list)
    analise_distratores: list[DistratorAnalise] = Field(default_factory=list)
    caracteristicas_item: CaracteristicasItem | None = None
    pedagogia: Pedagogia | None = None
    qualidade_anotacao: QualidadeAnotacao | None = None


class AnnotationRecord(BaseModel):
    """Wrapper stored in Mongo. `payload` is the raw JSON provided by the
    upstream AI, kept verbatim — no field is derived or transformed."""
    model_config = ConfigDict(extra="allow")
    item_id: str
    schema_version: str
    banca: str | None = None
    ano: int | None = None
    caderno: str | None = None
    numero: int | None = None
    disciplina: str | None = None
    payload: dict[str, Any]
    received_at: str = Field(default_factory=_now_iso)
    updated_at: str = Field(default_factory=_now_iso)
