"""
Ontologia Cognitiva Sapiens - Semente inicial.
Estrutura: 8 Domínios, 16 Competências, 28 Processos Cognitivos,
13 Tipos de Erro e Intervenções Pedagógicas.

Este arquivo serve apenas como semente. Toda a ontologia utilizada em
runtime pelo sistema é carregada da coleção MongoDB `ontologies`
(documento com is_active=True). Basta importar uma nova versão pela
página "Ontologia Cognitiva" para substituir esta.
"""

DEFAULT_ONTOLOGY = {
    "version": "1.0.0-seed",
    "name": "Ontologia Cognitiva Sapiens (ENEM)",
    "description": "Ontologia inicial para anotação cognitiva de questões do ENEM.",
    "dominios": [
        {"id": "DOM-QUANT", "nome": "Quantitativo",
         "descricao": "Domínio das grandezas, contagem, magnitude e operações numéricas. Envolve raciocínio aritmético, proporcional e algébrico aplicado à quantificação de fenômenos."},
        {"id": "DOM-ESPACO", "nome": "Espacial e Geométrico",
         "descricao": "Domínio das relações espaciais, visualização, geometria plana/espacial, coordenadas e transformações. Envolve leitura de figuras, mapas e diagramas."},
        {"id": "DOM-MUDANCA", "nome": "Mudança e Variação",
         "descricao": "Domínio das relações funcionais, taxa de variação, dependência entre grandezas, crescimento/decrescimento e modelagem dinâmica."},
        {"id": "DOM-INCERTEZA", "nome": "Incerteza e Dados",
         "descricao": "Domínio da probabilidade, estatística descritiva, análise de dados, amostragem e inferência informal."},
        {"id": "DOM-CAUSAL", "nome": "Causal e Argumentativo",
         "descricao": "Domínio da inferência causal, argumentação, contra-argumentação, identificação de premissas e conclusões em textos e situações."},
        {"id": "DOM-SISTEMICO", "nome": "Sistêmico e Interdisciplinar",
         "descricao": "Domínio das relações entre subsistemas, ciclos, retroalimentação e interdependência entre fenômenos naturais, sociais e tecnológicos."},
        {"id": "DOM-EXPERIMENTAL", "nome": "Experimental e Metodológico",
         "descricao": "Domínio do método científico, controle de variáveis, medição, interpretação de experimentos e leitura de resultados experimentais."},
        {"id": "DOM-ESTRUTURA", "nome": "Estrutura e Linguagem",
         "descricao": "Domínio das estruturas simbólicas, linguagens formais e naturais, sintaxe, semântica, análise textual e representação simbólica."},
    ],
    "competencias": [
        {"id": "COMP-01", "nome": "Interpretar textos verbais e não verbais", "dominio": "DOM-ESTRUTURA",
         "descricao": "Compreender enunciados, textos, tabelas, gráficos e imagens, identificando informações explícitas e implícitas."},
        {"id": "COMP-02", "nome": "Modelar situação-problema matematicamente", "dominio": "DOM-QUANT",
         "descricao": "Traduzir situações do mundo real em equações, funções, expressões numéricas ou modelos algébricos."},
        {"id": "COMP-03", "nome": "Raciocinar proporcionalmente", "dominio": "DOM-QUANT",
         "descricao": "Aplicar noções de razão, proporção, porcentagem e regra de três em contextos variados."},
        {"id": "COMP-04", "nome": "Interpretar representações geométricas", "dominio": "DOM-ESPACO",
         "descricao": "Ler, comparar e transformar figuras planas e espaciais, incluindo escalas e projeções."},
        {"id": "COMP-05", "nome": "Analisar variação e funções", "dominio": "DOM-MUDANCA",
         "descricao": "Identificar relações funcionais, taxas e comportamento de grandezas em função de outras."},
        {"id": "COMP-06", "nome": "Analisar dados estatísticos", "dominio": "DOM-INCERTEZA",
         "descricao": "Ler e interpretar medidas de tendência central, dispersão, gráficos e tabelas estatísticas."},
        {"id": "COMP-07", "nome": "Estimar probabilidades", "dominio": "DOM-INCERTEZA",
         "descricao": "Aplicar conceitos de probabilidade clássica, frequentista e condicional a situações concretas."},
        {"id": "COMP-08", "nome": "Argumentar com base em evidências", "dominio": "DOM-CAUSAL",
         "descricao": "Construir e avaliar argumentos, distinguindo evidência, opinião, causa e correlação."},
        {"id": "COMP-09", "nome": "Compreender fenômenos naturais", "dominio": "DOM-SISTEMICO",
         "descricao": "Explicar fenômenos físicos, químicos e biológicos a partir de modelos científicos."},
        {"id": "COMP-10", "nome": "Compreender fenômenos sociais e históricos", "dominio": "DOM-SISTEMICO",
         "descricao": "Analisar processos históricos, sociais e culturais reconhecendo múltiplas causalidades."},
        {"id": "COMP-11", "nome": "Aplicar método científico", "dominio": "DOM-EXPERIMENTAL",
         "descricao": "Formular hipóteses, controlar variáveis e interpretar experimentos e evidências."},
        {"id": "COMP-12", "nome": "Interpretar resultados experimentais", "dominio": "DOM-EXPERIMENTAL",
         "descricao": "Ler gráficos, tabelas e dados experimentais atribuindo significado científico."},
        {"id": "COMP-13", "nome": "Usar linguagem simbólica e formal", "dominio": "DOM-ESTRUTURA",
         "descricao": "Manipular equações, fórmulas, notações químicas, físicas e matemáticas."},
        {"id": "COMP-14", "nome": "Relacionar tecnologia e sociedade", "dominio": "DOM-SISTEMICO",
         "descricao": "Avaliar impactos e usos de tecnologias em contextos sociais, ambientais e éticos."},
        {"id": "COMP-15", "nome": "Analisar linguagens artísticas e culturais", "dominio": "DOM-ESTRUTURA",
         "descricao": "Compreender manifestações estéticas, literárias e culturais em seus contextos."},
        {"id": "COMP-16", "nome": "Tomar decisões sob incerteza", "dominio": "DOM-INCERTEZA",
         "descricao": "Escolher entre alternativas em situações de risco, aplicando análise probabilística."},
    ],
    "processos_cognitivos": [
        {"id": "PROC-01", "nome": "Identificar informação explícita", "categoria": "Leitura",
         "descricao": "Localizar dado literal presente no enunciado, gráfico ou figura."},
        {"id": "PROC-02", "nome": "Inferir informação implícita", "categoria": "Leitura",
         "descricao": "Deduzir dado não literal a partir de pistas textuais ou visuais."},
        {"id": "PROC-03", "nome": "Traduzir linguagem verbal em matemática", "categoria": "Modelagem",
         "descricao": "Converter enunciado em equação, expressão ou modelo."},
        {"id": "PROC-04", "nome": "Traduzir gráfico em relação funcional", "categoria": "Modelagem",
         "descricao": "Ler gráfico e associá-lo a uma função ou lei de formação."},
        {"id": "PROC-05", "nome": "Aplicar regra de três / proporção", "categoria": "Cálculo",
         "descricao": "Executar procedimento proporcional para resolver situação."},
        {"id": "PROC-06", "nome": "Calcular porcentagem", "categoria": "Cálculo",
         "descricao": "Aplicar operações percentuais em contexto real."},
        {"id": "PROC-07", "nome": "Operar com unidades e conversões", "categoria": "Cálculo",
         "descricao": "Transformar unidades de medida e verificar consistência dimensional."},
        {"id": "PROC-08", "nome": "Resolver equação de 1º ou 2º grau", "categoria": "Cálculo",
         "descricao": "Manipular algebricamente e encontrar raízes."},
        {"id": "PROC-09", "nome": "Identificar padrão / regularidade", "categoria": "Raciocínio indutivo",
         "descricao": "Reconhecer sequência ou regularidade em dados."},
        {"id": "PROC-10", "nome": "Formular hipótese", "categoria": "Investigação",
         "descricao": "Propor explicação testável a partir de observação."},
        {"id": "PROC-11", "nome": "Controlar variáveis", "categoria": "Investigação",
         "descricao": "Isolar fatores relevantes em análise experimental."},
        {"id": "PROC-12", "nome": "Comparar grandezas", "categoria": "Análise",
         "descricao": "Estabelecer relação de maior/menor/igual entre valores ou classes."},
        {"id": "PROC-13", "nome": "Estimar ordem de grandeza", "categoria": "Estimativa",
         "descricao": "Fornecer valor aproximado com base em pistas contextuais."},
        {"id": "PROC-14", "nome": "Ler tabela de dupla entrada", "categoria": "Leitura",
         "descricao": "Cruzar linhas e colunas para extrair valores."},
        {"id": "PROC-15", "nome": "Ler gráfico de barras/linhas", "categoria": "Leitura",
         "descricao": "Interpretar eixos, escalas e categorias em gráficos."},
        {"id": "PROC-16", "nome": "Interpretar figura geométrica", "categoria": "Visualização",
         "descricao": "Extrair informações métricas e relacionais de figuras."},
        {"id": "PROC-17", "nome": "Aplicar teorema de Pitágoras", "categoria": "Cálculo geométrico",
         "descricao": "Utilizar relação em triângulos retângulos."},
        {"id": "PROC-18", "nome": "Calcular área/volume", "categoria": "Cálculo geométrico",
         "descricao": "Aplicar fórmulas de figuras planas e sólidas."},
        {"id": "PROC-19", "nome": "Interpretar probabilidade condicional", "categoria": "Probabilidade",
         "descricao": "Avaliar dependência entre eventos."},
        {"id": "PROC-20", "nome": "Calcular média/mediana/moda", "categoria": "Estatística",
         "descricao": "Aplicar medidas de tendência central."},
        {"id": "PROC-21", "nome": "Analisar dispersão de dados", "categoria": "Estatística",
         "descricao": "Ler desvio, amplitude ou variância."},
        {"id": "PROC-22", "nome": "Identificar causa e efeito", "categoria": "Raciocínio causal",
         "descricao": "Distinguir causa, consequência e correlação em texto."},
        {"id": "PROC-23", "nome": "Avaliar validade de argumento", "categoria": "Argumentação",
         "descricao": "Julgar se conclusão decorre logicamente das premissas."},
        {"id": "PROC-24", "nome": "Contextualizar historicamente", "categoria": "Contextualização",
         "descricao": "Situar fenômeno em seu período e conjuntura."},
        {"id": "PROC-25", "nome": "Interpretar fórmula química/física", "categoria": "Simbólico",
         "descricao": "Ler notações, expoentes, subscritos e coeficientes."},
        {"id": "PROC-26", "nome": "Aplicar princípio de conservação", "categoria": "Ciências naturais",
         "descricao": "Usar conservação de energia, massa ou quantidade de movimento."},
        {"id": "PROC-27", "nome": "Sintetizar múltiplas fontes", "categoria": "Integração",
         "descricao": "Combinar informações de textos, gráficos e imagens."},
        {"id": "PROC-28", "nome": "Avaliar impacto socioambiental", "categoria": "Juízo de valor",
         "descricao": "Analisar consequências éticas, ambientais e sociais de práticas."},
    ],
    "tipos_erro": [
        {"id": "ERR-01", "nome": "Leitura literal deficiente",
         "descricao": "Aluno não localiza dado explícito no enunciado."},
        {"id": "ERR-02", "nome": "Inferência indevida",
         "descricao": "Aluno assume dados não presentes ou extrapola."},
        {"id": "ERR-03", "nome": "Erro de modelagem",
         "descricao": "Aluno traduz mal o enunciado para linguagem matemática."},
        {"id": "ERR-04", "nome": "Erro de conversão de unidades",
         "descricao": "Aluno mistura ou confunde unidades de medida."},
        {"id": "ERR-05", "nome": "Erro algébrico",
         "descricao": "Aluno comete erro em manipulação de equações ou expressões."},
        {"id": "ERR-06", "nome": "Confusão entre proporção direta e inversa",
         "descricao": "Aluno aplica regra proporcional incorreta."},
        {"id": "ERR-07", "nome": "Leitura equivocada de gráfico",
         "descricao": "Aluno confunde eixos, escalas ou categorias."},
        {"id": "ERR-08", "nome": "Confusão causa/correlação",
         "descricao": "Aluno interpreta correlação como causa."},
        {"id": "ERR-09", "nome": "Generalização indevida",
         "descricao": "Aluno estende conclusão de amostra pequena para o todo."},
        {"id": "ERR-10", "nome": "Ignorar variável de controle",
         "descricao": "Aluno desconsidera fator interveniente em experimento."},
        {"id": "ERR-11", "nome": "Erro de interpretação de fórmula",
         "descricao": "Aluno lê notação simbólica incorretamente."},
        {"id": "ERR-12", "nome": "Erro de estimativa/ordem de grandeza",
         "descricao": "Aluno oferece valor com magnitude incompatível."},
        {"id": "ERR-13", "nome": "Distrator plausível",
         "descricao": "Aluno é atraído por alternativa parcialmente correta ou baseada em armadilha."},
    ],
    "intervencoes_pedagogicas": [
        {"id": "INT-01", "nome": "Releitura guiada do enunciado",
         "descricao": "Ler o enunciado destacando dados explícitos antes de resolver."},
        {"id": "INT-02", "nome": "Diagrama de tradução",
         "descricao": "Construir esquema visual conectando enunciado e modelo matemático."},
        {"id": "INT-03", "nome": "Prática guiada de proporções",
         "descricao": "Sequência de problemas graduados em proporcionalidade."},
        {"id": "INT-04", "nome": "Análise crítica de gráficos",
         "descricao": "Exercícios de leitura consciente de eixos e escalas."},
        {"id": "INT-05", "nome": "Debate estruturado de argumentos",
         "descricao": "Prática dialogada de identificação de premissas e conclusões."},
        {"id": "INT-06", "nome": "Laboratório de estimativa",
         "descricao": "Atividades de estimativa de ordem de grandeza no cotidiano."},
        {"id": "INT-07", "nome": "Revisão de unidades e conversões",
         "descricao": "Bloco intensivo de conversões dimensionais."},
    ],
}
